
version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./package.json:/app/package.json
      - ./src:/app/src
      - ./public:/app/public
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ["npm", "run", "dev"]

  copy-dist:
    build: .
    volumes:
      - ./dist:/host/dist
    command: ["sh", "-c", "cp -r /app/dist/* /host/dist/"]

